name: CI & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Tests · Lint · Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Run lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      # Optionnel : stocker l’artefact pour les jobs de déploiement
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            ./apps/backend/dist
            ./apps/frontend/dist

  deploy-fly:
    name: Deploy to Fly.io
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: .
      - name: Deploy with flyctl
        uses: superfly/flyctl-actions@v1
        with:
          args: deploy --config fly.toml --dockerfile Dockerfile

  deploy-vercel:
    name: Deploy to Vercel
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Vercel CLI
        run: npm install -g vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: apps/frontend
          prod: true
