name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Tests · Lint · Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      # BACKEND: install, lint & test
      - name: Install dependencies (backend)
        working-directory: backend
        run: pnpm install
      - name: Lint backend
        working-directory: backend
        run: pnpm lint
      - name: Run tests (backend)
        working-directory: backend
        run: pnpm test

      # FRONTEND: install, lint, test & build
      - name: Install dependencies (frontend)
        working-directory: frontend
        run: pnpm install
      - name: Lint frontend
        working-directory: frontend
        run: pnpm lint
      - name: Run tests (frontend)
        working-directory: frontend
        run: pnpm test
      - name: Build frontend
        working-directory: frontend
        run: pnpm build

  deploy-fly:
    name: Deploy to Fly.io
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy with flyctl
        uses: superfly/flyctl-actions@v1
        with:
          args: deploy --config fly.toml --dockerfile Dockerfile

  deploy-vercel:
    name: Deploy frontend to Vercel
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Vercel CLI
        run: npm install -g vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend
          prod: true
